routes/web.php
            ->name('academic.class_edit');
    Route::post('academic/class/update/{id}', 'AcademicController@classCru')
            ->name('academic.class_update');
    Route::post('academic/class/status/{id}', 'AcademicController@classStatus')
            ->name('academic.class_status');

    // section
    Route::get('academic/section', 'AcademicController@sectionIndex')
            ->name('academic.section');
    Route::post('academic/section', 'AcademicController@sectionIndex')
            ->name('academic.section_destroy');
    Route::get('academic/section/create', 'AcademicController@sectionCru')
            ->name('academic.section_create');
    Route::post('academic/section/create', 'AcademicController@sectionCru')
            ->name('academic.section_store');
    Route::get('academic/section/edit/{id}', 'AcademicController@sectionCru')
            ->name('academic.section_edit');
    Route::post('academic/section/update/{id}', 'AcademicController@sectionCru')
            ->name('academic.section_update');
    Route::post('academic/section/status/{id}', 'AcademicController@sectionStatus')
            ->name('academic.section_status');

    // subject
    Route::get('academic/subject', 'AcademicController@subjectIndex')
            ->name('academic.subject');
    Route::post('academic/subject', 'AcademicController@subjectIndex')
            ->name('academic.subject_destroy');
    Route::get('academic/subject/create', 'AcademicController@subjectCru')
            ->name('academic.subject_create');
    Route::post('academic/subject/create', 'AcademicController@subjectCru')
            ->name('academic.subject_store');
    Route::get('academic/subject/edit/{id}', 'AcademicController@subjectCru')
            ->name('academic.subject_edit');
    Route::post('academic/subject/update/{id}', 'AcademicController@subjectCru')
            ->name('academic.subject_update');
    Route::post('academic/subject/status/{id}', 'AcademicController@subjectStatus')
            ->name('academic.subject_status');


    // teacher routes
    Route::resource('teacher', 'TeacherController');
    Route::post('teacher/status/{id}', 'TeacherController@changeStatus')
            ->name('teacher.status');

    // student routes
    Route::resource('student', 'StudentController');
    Route::post('student/status/{id}', 'StudentController@changeStatus')
            ->name('student.status');
    Route::get('student-list-by-filter', 'StudentController@studentListByFitler')
            ->name('student.list_by_fitler');

    // student attendance routes
    Route::get('student-attendance', 'StudentAttendanceController@index')->name('student_attendance.index');
    Route::any('student-attendance/create', 'StudentAttendanceController@create')->name('student_attendance.create');
    Route::post('student-attendance/store', 'StudentAttendanceController@store')->name('student_attendance.store');
    Route::post('student-attendance/status/{id}', 'StudentAttendanceController@changeStatus')
            ->name('student_attendance.status');
    Route::any('student-attendance/file-upload', 'StudentAttendanceController@createFromFile')
            ->name('student_attendance.create_file');
    Route::get('student-attendance/file-queue-status', 'StudentAttendanceController@fileQueueStatus')
            ->name('student_attendance.file_queue_status');


    // HRM
    //Employee
    Route::resource('hrm/employee', 'EmployeeController', ['as' => 'hrm']);
    Route::post('hrm/employee/status/{id}', 'EmployeeController@changeStatus')
            ->name('hrm.employee.status');
    // Leave
    Route::resource('hrm/leave', 'LeaveController', ['as' => 'hrm']);
    Route::resource('hrm/work_outside', 'WorkOutsideController', ['as' => 'hrm']);
    // policy
    Route::get('hrm/policy', 'EmployeeController@hrmPolicy')
            ->name('hrm.policy');
    Route::post('hrm/policy', 'EmployeeController@hrmPolicy')
            ->name('hrm.policy');

    // employee attendance routes
    Route::get('employee-attendance', 'EmployeeAttendanceController@index')->name('employee_attendance.index');
    Route::get('employee-attendance/create', 'EmployeeAttendanceController@create')->name('employee_attendance.create');
    Route::post('employee-attendance/create', 'EmployeeAttendanceController@store')->name('employee_attendance.store');
    Route::post('employee-attendance/status/{id}', 'EmployeeAttendanceController@changeStatus')
            ->name('employee_attendance.status');
    Route::any('employee-attendance/file-upload', 'EmployeeAttendanceController@createFromFile')
            ->name('employee_attendance.create_file');
    Route::get('employee-attendance/file-queue-status', 'EmployeeAttendanceController@fileQueueStatus')
            ->name('employee_attendance.file_queue_status');


    //exam
    Route::get('exam', 'ExamController@index')
            ->name('exam.index');
    Route::get('exam/create', 'ExamController@create')
            ->name('exam.create');
    Route::post('exam/store', 'ExamController@store')
            ->name('exam.store');
    Route::get('exam/edit/{id}', 'ExamController@edit')
            ->name('exam.edit');
    Route::post('exam/update/{id}', 'ExamController@update')
            ->name('exam.update');
    Route::post('exam/status/{id}', 'ExamController@changeStatus')
            ->name('exam.status');
    Route::post('exam/delete/{id}', 'ExamController@destroy')
            ->name('exam.destroy');
    //grade
    Route::get('exam/grade', 'ExamController@gradeIndex')
            ->name('exam.grade.index');
    Route::post('exam/grade', 'ExamController@gradeIndex')
            ->name('exam.grade.destroy');
    Route::get('exam/grade/create', 'ExamController@gradeCru')
            ->name('exam.grade.create');
    Route::post('exam/grade/create', 'ExamController@gradeCru')
            ->name('exam.grade.store');
    Route::get('exam/grade/edit/{id}', 'ExamController@gradeCru')
            ->name('exam.grade.edit');
    Route::post('exam/grade/update/{id}', 'ExamController@gradeCru')
            ->name('exam.grade.update');
    //exam rules
    Route::get('exam/rule', 'ExamController@ruleIndex')
            ->name('exam.rule.index');
    Route::post('exam/rule', 'ExamController@ruleIndex')
            ->name('exam.rule.destroy');
    Route::get('exam/rule/create', 'ExamController@ruleCreate')
            ->name('exam.rule.create');
    Route::post('exam/rule/create', 'ExamController@ruleCreate')
            ->name('exam.rule.store');
    Route::get('exam/rule/edit/{id}', 'ExamController@ruleEdit')
            ->name('exam.rule.edit');
    Route::post('exam/rule/update/{id}', 'ExamController@ruleEdit')
            ->name('exam.rule.update');

    //Marks
    Route::any('marks', 'MarkController@index')
            ->name('marks.index');
    Route::any('marks/create', 'MarkController@create')
            ->name('marks.create');
    Route::post('marks/store', 'MarkController@store')
            ->name('marks.store');
    Route::get('marks/edit/{id}', 'MarkController@edit')
            ->name('marks.edit');
    Route::post('marks/update/{id}', 'MarkController@update')
            ->name('marks.update');
    //result
    Route::any('result', 'MarkController@resultIndex')
            ->name('result.index');
    Route::any('result/generate', 'MarkController@resultGenerate')
            ->name('result.create');
    Route::any('result/delete', 'MarkController@resultDelete')
            ->name('result.delete');

    // Reporting

    Route::any('report/student-monthly-attendance', 'ReportController@studentMonthlyAttendance')
            ->name('report.student_monthly_attendance');
    Route::any('report/student-list', 'ReportController@studentList')
            ->name('report.student_list');
    Route::any('report/employee-list', 'ReportController@employeeList')
            ->name('report.employee_list');
    Route::any('report/employee-monthly-attendance', 'ReportController@employeeMonthlyAttendance')
            ->name('report.employee_monthly_attendance');
});

//web artisan routes
Route::get(
        '/student-attendance-file-queue-start/{code}', function ($code) {
    if ($code == "hr799") {
        try {
            echo '<br>Started student attendance processing...<br>';
            Artisan::call('attendance:seedStudent');
            echo '<br>Student attendance processing completed.<br>You will be redirect in 5 seconds.<br>';
            sleep(5);

            return redirect()->route('student_attendance.create_file')->with("success", "Students attendance saved and send sms successfully.");
        } catch (Exception $e) {
            Response::make($e->getMessage(), 500);
        }
    } else {
        App::abort(404);
    }
}
)->name('student_attendance_seeder');
Route::get(
        '/employee-attendance-file-queue-start/{code}', function ($code) {
    if ($code == "hr799") {
        try {
            echo '<br>Started employee attendance processing...<br>';
            Artisan::call('attendance:seedEmployee');
            echo '<br>Employee attendance processing completed.<br>You will be redirect in 5 seconds.<br>';
            sleep(5);

            return redirect()->route('employee_attendance.create_file')->with("success", "Employee attendance saved and notify successfully.");
        } catch (Exception $e) {
            Response::make($e->getMessage(), 500);
        }
    } else {
        App::abort(404);
    }
}
)->name('employee_attendance_seeder');

//dev routes
Route::get(
        '/make-link/{code}', function ($code) {
    if ($code !== '007') {
        return 'Wrong code!';
    }

    //check if developer mode enabled?
    if (!env('DEVELOPER_MODE_ENABLED', false)) {
        return "Please enable developer mode in '.env' file." . PHP_EOL . "set 'DEVELOPER_MODE_ENABLED=true'";
    }
    //remove first
    if (is_link(public_path('storage'))) {
        unlink(public_path('storage'));
    }

app/Http/Controllers/Backend/WorkOutsideController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Employee;
use App\Leave;
use App\WorkOutside;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;

class WorkOutsideController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $employee = $request->get('employee_id', 0);
        $work_date = $request->get('work_date', '');
        $employees = Employee::pluck('name','id')->prepend('All', 0);;

        $works = collect();
        if($request->has('filter')) {
            //need to implement filters here
            $works = WorkOutside::with('employee')
                ->whereEmployee($employee)
                ->whereWorkDate($work_date)
                ->get();
        }

        return view('backend.hrm.work_outside.list', compact(
            'works',
            'employees',
            'employee',
            'work_date'
        ));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $employees = Employee::pluck('name','id');
        $work = null;
        return view('backend.hrm.work_outside.add', compact('work', 'employees'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validate form
        $messages = [
            'document.max' => 'The :attribute size must be under 2mb.',
        ];

        $rules =  [
            'employee_id' => 'required|integer',
            'work_date' => 'min:10',
            'work_date_end' => 'nullable|min:10',
            'document' => 'nullable|mimes:jpeg,jpg,png,pdf,doc,docx,txt|max:2048',
            'description' => 'nullable|max:500',

        ];

        $this->validate($request, $rules);


        //custom validation goes here
        $dayCount = 1;
        $leaveDateStart = Carbon::createFromFormat('d/m/Y',$request->get('work_date'));
        $leaveDateEnd = null;
        if(strlen($request->get('work_date_end',''))) {
            $leaveDateEnd = Carbon::createFromFormat('d/m/Y', $request->get('work_date_end'));
            $dayCount = $leaveDateEnd->diff($leaveDateStart)->format("%a")+1;

            if($leaveDateEnd<$leaveDateStart){
                return redirect()->back()->with('error','Work End date can\'t be less than start date!');
            }
        }

        $dateList = [$leaveDateStart->format('Y-m-d')];
        if($leaveDateEnd){
            $startDate = $leaveDateStart->copy();
            $startDate->addDay(1);
            while ($startDate->lte($leaveDateEnd)){
                $dateList[] = $startDate->format('Y-m-d');
                $startDate->addDay(1);
            }
        }
        $haveLeave = Leave::where('employee_id', $request->get('employee_id',0))
            ->whereIn('status',[1,2]) //pending, approved
            ->whereIn('leave_date', $dateList)
            ->count();

        if($haveLeave){
            $message = 'This employee has leave schedule';
            if($leaveDateEnd){
                $message .= ' inside '.$leaveDateStart->format('d/m/Y').' to '.$leaveDateEnd->format('d/m/Y');
            }
            else{
                $message .= ' on '.$leaveDateStart->format('d/m/Y');
            }
            return redirect()->back()->with('error', $message);
        }

        $data = $request->all();
        if($request->hasFile('document')) {
            $storagepath = $request->file('document')->store('public/work_outside');
            $fileName = basename($storagepath);
            $data['document'] = $fileName;
        }
        else{
            $data['document'] = $request->get('oldDocument','');
        }

        if(strlen($request->get('work_date_end',''))){

            $start_time = strtotime($leaveDateStart);
            $end_time = strtotime($leaveDateEnd);
            for($i=$start_time; $i<=$end_time; $i+=86400)
            {
                $data['work_date'] = date('d/m/Y', $i);
                WorkOutside::create($data);

            }

            $message = $dayCount." days work outside added!";

        }
        else {
            // now save employee
            WorkOutside::create($data);
            $message = "Work outside added!";
        }

        return redirect()->route('hrm.work_outside.create')->with('success', $message);
    }



    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\WorkOutside  $workOutside
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $work = WorkOutside::findOrFail($id);
        return view('backend.hrm.work_outside.add', compact('work'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\WorkOutside  $workOutside
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $work = WorkOutside::findOrFail($id);

            //validate form
            $messages = [
                'document.max' => 'The :attribute size must be under 2mb.',
            ];

            $rules =  [
                'work_date' => 'min:10',
                'document' => 'nullable|mimes:jpeg,jpg,png,pdf,doc,docx,txt|max:2048',
                'description' => 'nullable|max:500',

            ];


        $this->validate($request, $rules);
        $workDate = Carbon::createFromFormat('d/m/Y',$request->get('work_date'))->format('Y-m-d');
        $haveLeave = Leave::where('employee_id', $work->employee_id)
            ->whereIn('status',[1,2]) //pending, approved
            ->whereDate('leave_date', $workDate)
            ->count();
        if($haveLeave){
            $message = 'This employee has leave schedule  on '.$request->get('work_date');
            return redirect()->back()->with('error', $message);
        }

        $data = $request->all();
        unset($data['employee_id']);

        if($request->hasFile('document')) {
            $storagepath = $request->file('document')->store('public/work_outside');
            $fileName = basename($storagepath);
            $data['document'] = $fileName;

            //if file change then delete old one
            $oldFile = $request->get('oldDocument','');
            if( $oldFile != ''){
                $file_path = "public/work_outside/".$oldFile;
                Storage::delete($file_path);
            }
        }
        else{
            $data['document'] = $request->get('oldDocument','');
        }

        $work->fill($data);
        $work->save();


        return redirect()->route('hrm.work_outside.index')->with('success', 'Record Updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\WorkOutside  $workOutside
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $work = WorkOutside::findOrFail($id);
        $work->delete();

        return redirect()->route('hrm.work_outside.index')->with('success', 'Record deleted!');
    }
}

resources/views/backend/hrm/work_outside/add.blade.php
<!-- Master page  -->
@extends('backend.layouts.master')

<!-- Page title -->
@section('pageTitle') Work Outside @endsection
<!-- End block -->

<!-- BEGIN PAGE CONTENT-->
@section('pageContent')
    <!-- Section header -->
    <section class="content-header">
        <h1>
            Work Outside
            <small>@if($work) Modifier @else Ajouter @endif</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{URL::route('user.dashboard')}}"><i class="fa fa-dashboard"></i> Tableau de bord</a></li>
            <li><a href="{{URL::route('hrm.work_outside.index')}}"><i class="fa fa-sign-out"></i> Work Outside</a></li>
            <li class="active">@if($work) Modifier @else Ajouter @endif</li>
        </ol>
    </section>
    <!-- ./Section header -->
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-info">
                    <form novalidate id="entryForm" action="@if($work) {{URL::Route('hrm.work_outside.update', $work->id)}} @else {{URL::Route('hrm.work_outside.store')}} @endif" method="post" enctype="multipart/form-data">
                        <div class="box-header">
                            <div class="callout callout-danger">
                                <p><b>Note:</b> Create a employee before create new work outside.</p>
                            </div>
                        </div>
                        <div class="box-body">
                            @csrf
                            @if($work)  {{ method_field('PATCH') }} @endif
                            <div class="row">
                                @if(!$work)
                                <div class="col-md-4">
                                    <div class="form-group has-feedback">
                                        <label for="employee_id">Employee<span class="text-danger">*</span></label>
                                        {!! Form::select('employee_id', $employees, null , ['placeholder' => 'Pick a employee...','class' => 'form-control select2', 'required' => 'true']) !!}
                                        <span class="form-control-feedback"></span>
                                        <span class="text-danger">{{ $errors->first('employee_id') }}</span>
                                    </div>
                                </div>
                                @endif
                                <div class=" @if(!$work)col-md-4 @else col-md-6 @endif">
                                    <div class="form-group has-feedback">
                                        <label for="work_date">Work Date @if(!$work)Start @endif<span class="text-danger">*</span></label>
                                        <input type='text' class="form-control date_picker"  readonly name="work_date" placeholder="date" value="@if($work){{$work->work_date->format('d/m/Y')}}@else{{old('work_date') }}@endif" required minlength="10" maxlength="10" />
                                        <span class="fa fa-calendar form-control-feedback"></span>
                                        <span class="text-danger">{{ $errors->first('work_date') }}</span>
                                    </div>
                                </div>
                                    @if(!$work)
                                    <div class="col-md-4">
                                    <div class="form-group has-feedback">
                                        <label for="work_date_end">Work Date end</label>
                                        <input type='text' class="form-control date_picker_with_clear"  readonly name="work_date_end" placeholder="date" value="" minlength="10" maxlength="10" />
                                        <span class="fa fa-calendar form-control-feedback"></span>
                                        <span class="text-danger">{{ $errors->first('work_date_end') }}</span>
                                    </div>
                                </div>
                                @endif
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group has-feedback">
                                        <label for="document">Document <span class="text-black">[max 2mb]</span></label>
                                        <input  type="file" class="form-control" accept=".jpeg, .jpg, .png, .pdf, .doc, .docx, .txt" name="document" placeholder="Work Outside paper">
                                        @if($work && isset($work->document))
                                            <input type="hidden" name="oldDocument" value="{{$work->document}}">
                                        @endif
                                        <span class="glyphicon glyphicon-open-file form-control-feedback" style="top:25px;"></span>
                                        <span class="text-danger">{{ $errors->first('document') }}</span>
                                    </div>
                                </div>
                                <div class="col-md-8">
                                    <div class="form-group has-feedback">
                                        <label for="description">Description</label>
                                        <textarea name="description" class="form-control"  maxlength="500">@if($work){{ $work->description }}@endif</textarea>
                                        <span class="fa fa-location-arrow form-control-feedback"></span>
                                        <span class="text-danger">{{ $errors->first('description') }}</span>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <!-- /.box-body -->
                        <div class="box-footer">
                            <a href="{{URL::route('hrm.work_outside.index')}}" class="btn btn-default">Annuler</a>
                            <button type="submit" class="btn btn-info pull-right"><i class="fa @if($work) fa-refresh @else fa-plus-circle @endif"></i> @if($work) Modifier @else Ajouter @endif</button>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- /.content -->
@endsection
<!-- END PAGE CONTENT-->

<!-- BEGIN PAGE JS-->
@section('extraScript')
    <script type="text/javascript">
        $(document).ready(function () {
            Generic.initCommonPageJS();
        });
    </script>
@endsection
<!-- END PAGE JS-->

resources/views/backend/hrm/work_outside/list.blade.php
<!-- Master page  -->
@extends('backend.layouts.master')

<!-- Page title -->
@section('pageTitle')  Work Outside @endsection
<!-- End block -->



<!-- BEGIN PAGE CONTENT-->
@section('pageContent')
    <!-- Section header -->
    <section class="content-header">
        <h1>
            Work Outside
            
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{URL::route('user.dashboard')}}"><i class="fa fa-dashboard"></i> Tableau de bord</a></li>
            <li class="active">Work Outside</li>
        </ol>
    </section>
    <!-- ./Section header -->
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-info">
                    <div class="box-header border">
                        <h3 class="text-info" style="margin-left: 10px;">Filters</h3>
                        <div class="box-tools pull-right">
                            <a class="btn btn-info btn-sm" href="{{ URL::route('hrm.work_outside.create') }}"><i class="fa fa-plus-circle"></i> Ajouter</a>
                        </div>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body margin-top-20">
                        <div class="row">
                            <div class="col-md-12">
                                <form action="" method="get" enctype="multipart/form-data">
                                    <input type="hidden" name="filter" value="1">
                                    <div class="row">
                                        <div class="col-md-3">
                                            <div class="form-group has-feedback">
                                                {!! Form::select('employee_id', $employees, $employee , ['class' => 'form-control select2']) !!}
                                            </div>
                                        </div>
                                        <div class="col-md-2">
                                            <div class="form-group has-feedback">
                                                <input type='text' class="form-control date_picker_with_clear"  readonly name="work_date" placeholder="date" value="@if($work_date){{$work_date}} @endif" required minlength="10" maxlength="10" />
                                                <span class="fa fa-calendar form-control-feedback"></span>
                                            </div>
                                        </div>

                                        <div class="col-md-2">
                                            <button class="btn btn-info btn-sm" type="submit"><i class="fa fa-list"></i> Get List</button>

                                        </div>

                                    </div>

                                </form>
                            </div>
                        </div>
                        <div class="table-responsive">
                            <table id="listDataTableWithSearch" class="table table-bordered table-striped list_view_table display responsive no-wrap" width="100%">
                                <thead>
                                <tr>
                                    <th width="5%">#</th>
                                    <th width="30%">Employee</th>
                                    <th width="10%">Date</th>
                                    <th class="notexport" width="5%">Document</th>
                                    <th width="30%">Note</th>
                                    <th class="notexport" width="20%">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($works as $work)
                                    <tr>
                                        <td>
                                            {{$loop->iteration}}
                                        </td>
                                        <td>{{ $work->employee->name }}</td>
                                        <td>{{ $work->work_date->format('d/m/Y') }}</td>
                                        <td>
                                            @if($work->document)
                                                <a target="_blank" href="{{asset('storage/work_outside/'.$work->document)}}" class="btn btn-link"> <i class="fa fa-2x fa-download"></i></a>
                                            @endif
                                        </td>
                                        <td>{{ $work->description }}</td>

                                        <td>
                                            <!-- todo: have problem in mobile device -->
                                                <div class="btn-group">
                                                    <a title="Edit"  href="{{URL::route('hrm.work_outside.edit',$work->id)}}"  class="btn btn-primary btn-sm"><i class="fa fa-edit"></i>
                                                    </a>
                                                </div>

                                            <div class="btn-group">
                                                <form  class="myAction" method="POST" action="{{URL::route('hrm.work_outside.destroy',$work->id)}}">
                                                    @csrf
                                                    {{ method_field('delete') }}
                                                    <input type="hidden" name="hiddenId" value="{{$work->id}}">
                                                    <button type="submit" class="btn btn-danger btn-sm" title="Delete">
                                                        <i class="fa fa-fw fa-trash"></i>
                                                    </button>
                                                </form>
                                            </div>

                                        </td>
                                    </tr>
                                @endforeach

                                </tbody>
                                <tfoot>
                                <tr>
                                    <th width="5%">#</th>
                                    <th width="30%">Employee</th>
                                    <th width="10%">Date</th>
                                    <th class="notexport" width="5%">Document</th>
                                    <th width="30%">Note</th>
                                    <th class="notexport" width="20%">Action</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                    <!-- /.box-body -->
                </div>
            </div>
        </div>

    </section>
    <!-- /.content -->
@endsection
<!-- END PAGE CONTENT-->

<!-- BEGIN PAGE JS-->
@section('extraScript')
    <script type="text/javascript">
        $(document).ready(function () {
            window.excludeFilterComlumns = [0,3,4,5];
            Generic.initCommonPageJS();
            Generic.initDeleteDialog();
        });
    </script>
@endsection
<!-- END PAGE JS-->